# Generated by Django 6.0.7 on 2026-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('contacto', models.CharField(blank=True, max_length=150, verbose_name='Contacto')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
