# Generated by Django 6.0.7 on 2026-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_delivery_deliverydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADA', 'Finalizada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20),
        ),
    ]
