# Generated by Django 6.0.7 on 2026-07-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_delivery_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterModelOptions(
            name='deliverydetail',
            options={'verbose_name': 'Detalle de Entrega', 'verbose_name_plural': 'Detalles de Entrega'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
    ]
