# Generated by Django 6.0.7 on 2026-08-04 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_alter_delivery_options_alter_deliverydetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
