# Generated by Django 6.0.7 on 2026-08-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Recepción', 'verbose_name_plural': 'Recepciones'},
        ),
        migrations.AlterModelOptions(
            name='receiptdetail',
            options={'verbose_name': 'Detalle de Recepción', 'verbose_name_plural': 'Detalles de Recepción'},
        ),
    ]
