# Generated by Django 6.0.7 on 2026-07-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(choices=[('ALMACENISTA', 'Almacenista'), ('RESIDENTE', 'Residente'), ('SUPERVISOR CIVIL', 'Supervisor Civil'), ('SUPERVISOR ELECTRICO', 'Supervisor Eléctrico'), ('SUPERVISOR MECANICO', 'Supervisor Mecánico')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
